### ISSUE TITLE
dear Dr huang

### ISSUE THREAD

**Issue by liyuan3970** [hhuangwx/cmaps#2]
您好，我是一名即将入职的天气预报员，我看了您的cmaps库，很受启发，目前对于ncl的调色板，只有您的库能够很好的移植到python上，但是依然存在一些问题，比如我想用ncl色板特定的颜色填充等值线，cmaps并不能很好的根据ncl的调色板自定义colormap，此外您的show方法仅能查看颜色，但并不能查看ncl颜色的色号，因此在您的基础上进行了改进,地址在https://github.com/liyuan3970/ncmap；使用样例和数据在example目录中（https://github.com/liyuan3970/ncmap/blob/master/example/example/example.md），期待您的参观，共同进步！！

**Comment by hhuangwx** [comment]
感谢您的分享。事实上，我的库已经提供了slice功能，可以选择特定的等值线。此外，由于colormap的使用较为频繁，因此，本库的逻辑为尽量简单为主。Matplotlib已经提供了很多从值进行构建colormap的方法，并且提供了插值功能，本库也没有重复。不过您给了我一些思考，我后面会考虑推出保存colormap的方法，并提供插值功能，这样方便用户进行colormap的添加。谢谢。
