### ISSUE TITLE
Pypi / Conda-forge package

### ISSUE THREAD

**Issue by jhamman** [hhuangwx/cmaps#3]
Would you be willing to package `cmaps` into a pypi package? This would allow people to easily install the package (`pip install cmaps`) and would help downstream users incorporate the package as a dependency. Ideally, this would also lead to a conda-forge package too.

Perhaps @bonnland or @andersy005 would be willing to help with this.

**Comment by hhuangwx** [comment]
It's done. Thank you.

**Comment by jhamman** [comment]
Thanks @hhuangwx!
