### ISSUE TITLE
Only first file in CMAP_DIR is read and parser returns before registering reversed colormap.

### ISSUE THREAD

**Issue by CalUWxBill** [hhuangwx/cmaps#4]
I noticed only one of my custom .rgb files was read and that the colormap that appends '_r' isn't being added.  I believe this issue occurs because the try..except is performed before changing cname, therefore cname is already registered and _parse_cmaps returns before the reverse colormap is returned.  So, in file cmaps.template line 62 should be moved up above line 57.

Also, anytime there is a .rgb that happens to match an already registered colormap name it won't continue to register the rest of the .rgb files in CMAP_DIR.  This may require even further modifications to the try..except.

**Comment by hhuangwx** [comment]
Got it, I'll fix it when I have time.

**Comment by hhuangwx** [comment]
Solved, thank you for the issue!
